---
title: "Amostra alunos CCC x PPGCC"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_bw())

library(broom)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

```{r read}
dados = read.csv2(here::here("data/campeonato-brasileiro-full.csv"))

glimpse(dados)
```

1. Jogos aos domingos têm mais gols que jogos às quartas? 

```{r}
dados %>% 
    filter(dia == "Domingo")
    ggplot(aes(x = sono_semana)) + 
    geom_histogram(binwidth = 1, boundary = 0) + 
    facet_wrap(~ turma, 
               ncol = 1)

dados %>% 
    ggplot(aes(x = sono_fds)) + 
    geom_histogram(binwidth = 1, boundary = 0) + 
    facet_wrap(~ turma, 
               ncol = 1) + 
    xlim(5, 10)
```

## Com ICs

### FDS

```{r}
theta_diferenca_fds = function(d, i){
    sonos = d %>% 
        slice(i) %>% 
        group_by(turma) %>% 
        summarise(sono = mean(sono_fds)) 
    
    cdd = sonos %>% filter(turma == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}


theta_diferenca_fds(dados, 1:NROW(dados))
```

```{r}
library(boot)
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

### Semana


```{r}
theta_diferenca_semana = function(d, i){
    sonos = d %>% 
        slice(i) %>% 
        group_by(turma) %>% 
        summarise(sono = mean(sono_semana)) 
    
    cdd = sonos %>% filter(turma == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}


theta_diferenca_semana(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

## Com teste de hipótese

### FDS

```{r}
theta_embaralhado = function(d){
    sonos = d %>% 
        mutate(turma_embaralhada = sample(turma, n())) %>% 
        group_by(turma_embaralhada) %>% 
        summarise(sono = mean(sono_fds)) 
    
    cdd = sonos %>% filter(turma_embaralhada == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma_embaralhada == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}

theta_embaralhado(dados)
```

```{r}
diffs1 = replicate(5000, {theta_embaralhado(dados)})

tibble(diferenca = diffs1) %>% 
  ggplot(aes(x = diferenca)) + 
  # geom_histogram(binwidth = .2, fill = "white", color = "darkgreen") + 
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diferenca_fds(dados, 1:NROW(dados)), 
             color = "orange") + 
    geom_vline(xintercept = - theta_diferenca_fds(dados, 1:NROW(dados)), 
             color = "orange")
```

```{r}
mean(abs(diffs) >= abs(theta_diferenca_fds(dados, 1:NROW(dados))))
```

```{r}
library(coin)

oneway_test(sono_fds ~ as.factor(turma),
            data = dados,
            distribution = approximate(B = 5000))
```

```{r}
library(resample)

p = permutationTest2(dados, 
                     mean(sono_fds), 
                     treatment = as.factor(turma))

p$stats$PValue
```

## Semana

```{r}
theta_emb_semana = function(d){
    sonos = d %>% 
        mutate(turma_embaralhada = sample(turma, n())) %>% 
        group_by(turma_embaralhada) %>% 
        summarise(sono = mean(sono_semana)) 
    
    cdd = sonos %>% filter(turma_embaralhada == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma_embaralhada == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}

theta_emb_semana(dados)

diffs = replicate(2000, {theta_emb_semana(dados)})

tibble(diferenca = diffs) %>% 
  ggplot(aes(x = diferenca)) + 
  # geom_histogram(binwidth = .2, fill = "white", color = "darkgreen") +
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diferenca_semana(dados, 1:NROW(dados)), 
             color = "orange") + 
    geom_vline(xintercept = -theta_diferenca_semana(dados, 1:NROW(dados)), 
             color = "orange")

sum(abs(diffs) >= abs(theta_diferenca_semana(dados, 1:NROW(dados)))) / length(diffs)
```

```{r}
library(resample)

p = permutationTest2(dados, 
                     mean(sono_semana), 
                     treatment = turma)

p$stats$PValue
```
